"""pyeffect: a fully typed functional core for Python."""

from pyeffect.codec import (
    Codec,
    ResultDeserializationError,
    ResultSerializationError,
    from_dict,
)
from pyeffect.compose import (
    compose,
    constant,
    curry,
    flip,
    identity,
    lift,
    lift2,
    lift3,
    partial,
    tap,
    unpack,
)
from pyeffect.do import do
from pyeffect.effect import Effect, do_effect, sequence
from pyeffect.option import (
    Nothing,
    Option,
    Some,
    UnwrapNothingError,
    flatten,
    from_optional,
)
from pyeffect.panic import Panic, is_panic, panic
from pyeffect.pipe import pipe
from pyeffect.result import (
    Err,
    ErrorContext,
    Ok,
    Result,
    UnwrapError,
    attempt,
    guard,
    is_err,
    is_ok,
    partition,
    recover,
    traverse,
)
from pyeffect.retry import Backoff, Policy, retry
from pyeffect.tagged import (
    MatchError,
    TaggedError,
    UnhandledException,
    match_error,
    match_error_partial,
)

__all__ = [
    "Backoff",
    "Codec",
    "Effect",
    "Err",
    "ErrorContext",
    "MatchError",
    "Nothing",
    "Ok",
    "Option",
    "Panic",
    "Policy",
    "Result",
    "ResultDeserializationError",
    "ResultSerializationError",
    "Some",
    "TaggedError",
    "UnhandledException",
    "UnwrapError",
    "UnwrapNothingError",
    "attempt",
    "compose",
    "constant",
    "curry",
    "do",
    "do_effect",
    "flatten",
    "flip",
    "from_dict",
    "from_optional",
    "guard",
    "identity",
    "is_err",
    "is_ok",
    "is_panic",
    "lift",
    "lift2",
    "lift3",
    "match_error",
    "match_error_partial",
    "panic",
    "partial",
    "partition",
    "pipe",
    "recover",
    "retry",
    "sequence",
    "tap",
    "traverse",
    "unpack",
]
